"use client"
import Link from 'next/link'
import './login.css'
import { usePathname } from 'next/navigation'

// export const metadata = {
//      title: 'Login',
//      description: 'Generated by create next app',
// }

export default function LoginLayout({ children }) {
     const pathName = usePathname();
     console.log(pathName);
     return (
          <div>
               <nav>
                    <ul>
                         <li><Link href={"/"}>Home</Link></li>
                         <li><Link href={"/login"}>Login</Link></li>
                         <li><Link href={"/register"}>Register</Link></li>
                         {
                              pathName == "/login/studentlogin" ?
                               <li><Link href={"/login/teacherlogin"}>Teachers Login</Link></li>
                              :<li><Link href={"/login/studentlogin"}>Student Login</Link></li>
                         }
                    </ul>
               </nav>
               <div>{children}</div>
          </div>
     )
}
