// import { Inter } from 'next/font/google'
// import { Roboto } from 'next/font/google';
import { Poppins } from 'next/font/google';

import './globals.css'
// const inter = Inter({ subsets: ['latin'] })
// const roboto = Roboto({ 
//   subsets: ['latin'], 
//   display: 'swap',
//   weight: ["100","300","400","500","700","900"]
//  })
const poppins = Poppins({ 
  subsets: ['latin'], 
  display: 'swap',
  weight: ["100","300","400","500","700","900"]
 })
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  )
}
