"use client"
import Link from 'next/link'
import './register.css'
import { usePathname } from 'next/navigation'

// export const metadata = {
//      title: 'Login',
//      description: 'Generated by create next app',
// }

export default function RegisterLayout({ children }) {
     const pathName = usePathname();
     console.log(pathName);
     return (
          <div>
               <nav>
                    <ul>
                         <li><Link href={"/"}>Home</Link></li>
                         <li><Link href={"/login"}>Login</Link></li>
                         <li><Link href={"/register"}>Register</Link></li>
                    </ul>
               </nav>
               <div>{children}</div>
          </div>
     )
}
